In [1]:
%matplotlib inline

# 什么是 PyTorch
一个基于 Python 的科学计算框架，致力于解决两个问题
* 在 GPU 计算上取代 Numpy
* 作为一个深度学习框架，提供尽可能的灵活度和计算速度

# 开始
Tensors
Tensor 张量，和 Numpy 里的 ndarrays 比较类似，不一样的是，Tensor 可以使用 GPU 来加速计算。

In [11]:
from __future__ import print_function
import torch

> An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

构建一个 5x3 的矩阵，如下：

In [14]:
x = torch.empty(5,3)
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


构建一个随机生成的矩阵

In [5]:
x = torch.rand(5,3)
print(x)

tensor([[0.9141, 0.1189, 0.8995],
        [0.2114, 0.1084, 0.0872],
        [0.9090, 0.4823, 0.4218],
        [0.5425, 0.4988, 0.1729],
        [0.6823, 0.8399, 0.7416]])


构建一个零矩阵，数据类型为long

In [7]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


从数据直接构建一个张量

In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


从已知张量构建张量

In [25]:
x = x.new_ones(5, 3, dtype = torch. double)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.1107, -0.8799, -0.5256],
        [ 0.7648, -0.4169,  0.3146],
        [ 0.6888, -0.7933,  0.0447],
        [-1.2212, -0.4439,  0.3204],
        [-0.1285,  1.6755,  1.0976]])


查看它的大小

In [10]:
print(x.size())

torch.Size([5, 3])


> `torch.size` 本质上是一个 tuple，所以它支持 tuple 的所有操作

# 运算
每种运算有多重操作的语法。

加法：语法一

In [16]:
y = torch.rand(5,3)
print(x + y)

tensor([[0.2605, 0.5445, 0.6920],
        [0.8372, 0.5105, 0.1438],
        [0.2147, 0.3049, 0.1512],
        [0.7614, 0.1301, 0.3434],
        [0.6581, 0.2526, 0.6738]])


加法：语法二

In [18]:
print(torch.add(x, y))

tensor([[0.2605, 0.5445, 0.6920],
        [0.8372, 0.5105, 0.1438],
        [0.2147, 0.3049, 0.1512],
        [0.7614, 0.1301, 0.3434],
        [0.6581, 0.2526, 0.6738]])


增加一个输出张量作为一个参数

In [22]:
result = torch.empty(5, 3) # 这句声明也可以去掉
torch.add(x, y, out=result)
print(result)

tensor([[0.2605, 0.5445, 0.6920],
        [0.8372, 0.5105, 0.1438],
        [0.2147, 0.3049, 0.1512],
        [0.7614, 0.1301, 0.3434],
        [0.6581, 0.2526, 0.6738]])


补充：in-place 方法，有点类似 C++ 里的 += 

In [23]:
y.add_(x)
print(y)

tensor([[0.2605, 0.5445, 0.6920],
        [0.8372, 0.5105, 0.1438],
        [0.2147, 0.3049, 0.1512],
        [0.7614, 0.1301, 0.3434],
        [0.6581, 0.2526, 0.6738]])


> Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change x.

你可以使用标准的类似 numpy 的索引，来提取行或者列。

In [26]:
print(x)

print(x[:,1]) # 提取列

print(x[1,:]) # 提取行

tensor([[-1.1107, -0.8799, -0.5256],
        [ 0.7648, -0.4169,  0.3146],
        [ 0.6888, -0.7933,  0.0447],
        [-1.2212, -0.4439,  0.3204],
        [-0.1285,  1.6755,  1.0976]])
tensor([-0.8799, -0.4169, -0.7933, -0.4439,  1.6755])
tensor([ 0.7648, -0.4169,  0.3146])


调整大小：如果要修改张量的长宽，可以使用 `torch.view`:

In [32]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果有一个单元素的张量，可以使用 `.item()` 来获取一个值作为 Python 数值

In [33]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3458])
0.3457903563976288


其他运算，包括转置，索引，切片，运算，线性代数，随机数字等，查看 [这里](https://pytorch.org/docs/stable/torch.html)

# NumPy Bridge

Torch Tensor 与 Numpy 数组之间互相转换是非常方便的
## 将 Torch Tensor 转换为 Numpy 数组

In [35]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [36]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


查看值如何变动

In [37]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## 将 Numpy 数组转换为 Torch Tensor

In [38]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


除CharTensor之外，CPU上的所有张量都支持转换为NumPy并返回。